pub(super) const EMOJI: &[(u8, &str, &str, &str, bool)] = &[
    (0, "😀", "big smile", "happy grin cheerful", false),
    (
        0,
        "😃",
        "smiling with open eyes",
        "happy grin excited",
        false,
    ),
    (
        0,
        "😄",
        "smiling with happy eyes",
        "joy cheerful laugh",
        false,
    ),
    (0, "😁", "beaming smile", "grin teeth happy", false),
    (
        0,
        "😆",
        "laughing with closed eyes",
        "haha lol funny",
        false,
    ),
    (
        0,
        "😅",
        "smiling with sweat",
        "nervous relief awkward",
        false,
    ),
    (0, "🤣", "rolling with laughter", "rofl funny lol", false),
    (0, "😂", "laughing tears", "joy funny lol crying", false),
    (0, "🙂", "small smile", "happy okay", false),
    (0, "🙃", "upside down smile", "sarcasm silly ironic", false),
    (
        0,
        "🫠",
        "melting smile",
        "heat embarrassed overwhelmed",
        false,
    ),
    (0, "😉", "wink", "joke flirt", false),
    (0, "😊", "blushing smile", "happy shy sweet", false),
    (0, "😇", "angel smile", "innocent halo", false),
    (
        0,
        "🥰",
        "smiling with hearts",
        "love adore affection",
        false,
    ),
    (0, "😍", "heart eyes", "love crush adore", false),
    (0, "🤩", "star eyes", "amazed excited wow", false),
    (0, "😘", "blowing a kiss", "love affection", false),
    (0, "😗", "kissing", "kiss affection", false),
    (0, "☺️", "warm smile", "happy blush", false),
    (0, "😚", "kissing with closed eyes", "kiss love", false),
    (0, "😙", "kissing with smiling eyes", "kiss happy", false),
    (
        0,
        "🥲",
        "smiling through a tear",
        "touched grateful bittersweet",
        false,
    ),
    (0, "😋", "enjoying food", "yum tasty delicious", false),
    (0, "😛", "tongue out", "playful silly", false),
    (0, "😜", "winking tongue", "joke cheeky silly", false),
    (0, "🤪", "wild face", "crazy goofy zany", false),
    (0, "😝", "squinting tongue", "playful silly", false),
    (0, "🤑", "money face", "rich cash dollar", false),
    (0, "🤗", "hugging face", "hug welcome warm", false),
    (0, "🤭", "hand over mouth", "oops giggle surprise", false),
    (0, "🫢", "surprised hand over mouth", "gasp shock", false),
    (0, "🫣", "peeking face", "shy scared embarrassed", false),
    (0, "🤫", "shushing", "quiet hush secret", false),
    (0, "🤔", "thinking", "hmm wonder question", false),
    (0, "🫡", "saluting", "respect yes salute", false),
    (0, "🤐", "zipped mouth", "secret silent", false),
    (
        0,
        "🤨",
        "raised eyebrow",
        "skeptical doubt suspicious",
        false,
    ),
    (0, "😐", "neutral face", "meh blank indifferent", false),
    (0, "😑", "expressionless", "unimpressed blank", false),
    (0, "😶", "no mouth", "speechless silent", false),
    (0, "🫥", "dotted face", "invisible hiding", false),
    (0, "😶‍🌫️", "face in clouds", "fog distracted confused", false),
    (0, "😏", "smirk", "flirt sly smug", false),
    (0, "😒", "unamused", "annoyed bored unimpressed", false),
    (0, "🙄", "rolling eyes", "annoyed whatever", false),
    (0, "😬", "grimacing", "awkward cringe nervous", false),
    (0, "😮‍💨", "exhaling", "sigh relief tired", false),
    (0, "🤥", "lying face", "lie pinocchio", false),
    (0, "🫨", "shaking face", "shocked earthquake stunned", false),
    (0, "🙂‍↔️", "shaking head no", "disagree refuse", false),
    (0, "🙂‍↕️", "nodding yes", "agree accept", false),
    (0, "😌", "relieved", "peace calm relaxed", false),
    (0, "😔", "downcast", "sad thoughtful", false),
    (0, "😪", "sleepy", "tired nap", false),
    (0, "🤤", "drooling", "want hungry delicious", false),
    (0, "😴", "sleeping", "sleep snooze tired", false),
    (0, "🫩", "bags under eyes", "exhausted sleepy tired", false),
    (0, "😷", "medical mask", "sick health flu", false),
    (0, "🤒", "thermometer face", "fever ill sick", false),
    (0, "🤕", "bandaged head", "hurt injured", false),
    (0, "🤢", "nauseated", "sick gross queasy", false),
    (0, "🤮", "vomiting", "sick puke", false),
    (0, "🤧", "sneezing", "cold tissue allergy", false),
    (0, "🥵", "hot face", "heat sweaty", false),
    (0, "🥶", "cold face", "freezing ice", false),
    (0, "🥴", "woozy", "dizzy drunk unwell", false),
    (0, "😵", "dazed face", "shock dizzy faint", false),
    (0, "😵‍💫", "spiral eyes", "dizzy hypnotized confused", false),
    (0, "🤯", "exploding head", "mindblown amazed", false),
    (0, "🤠", "cowboy face", "western hat", false),
    (0, "🥳", "party face", "celebrate birthday", false),
    (
        0,
        "🥸",
        "disguised face",
        "glasses moustache disguise",
        false,
    ),
    (0, "😎", "sunglasses smile", "cool sunny", false),
    (0, "🤓", "nerdy face", "geek glasses smart", false),
    (0, "🧐", "monocle face", "curious inspect", false),
    (0, "😕", "confused", "unsure puzzled", false),
    (0, "🫤", "diagonal mouth", "uncertain disappointed", false),
    (0, "😟", "worried", "concern anxious", false),
    (0, "🙁", "small frown", "sad unhappy", false),
    (0, "☹️", "frowning face", "sad unhappy", false),
    (0, "😮", "open mouth", "surprised wow", false),
    (0, "😯", "hushed face", "surprised quiet", false),
    (0, "😲", "astonished", "amazed shocked", false),
    (0, "😳", "flushed face", "embarrassed blush", false),
    (0, "🥺", "pleading eyes", "please puppy beg", false),
    (
        0,
        "🥹",
        "holding back tears",
        "touched grateful emotional",
        false,
    ),
    (0, "😦", "frown with open mouth", "upset shocked", false),
    (0, "😧", "anguished", "worried pain", false),
    (0, "😨", "fearful", "afraid scared", false),
    (0, "😰", "anxious with sweat", "nervous worried", false),
    (0, "😥", "sad with a tear", "disappointed relieved", false),
    (0, "😢", "crying face", "sad tear", false),
    (0, "😭", "sobbing", "cry sad tears", false),
    (0, "😱", "screaming", "fear horror shocked", false),
    (0, "😖", "confounded", "frustrated upset", false),
    (0, "😣", "struggling", "persevere pain", false),
    (0, "😞", "disappointed", "sad letdown", false),
    (0, "😓", "downcast with sweat", "stressed tired", false),
    (0, "😩", "weary", "tired frustrated", false),
    (0, "😫", "tired face", "exhausted frustrated", false),
    (0, "🥱", "yawning", "bored sleepy", false),
    (0, "😤", "huffing", "angry determined steam", false),
    (0, "😡", "angry red face", "rage mad furious", false),
    (0, "😠", "angry face", "mad annoyed", false),
    (0, "🤬", "swearing face", "curse angry rage", false),
    (0, "😈", "smiling devil", "mischief evil horns", false),
    (0, "👿", "angry devil", "evil horns", false),
    (0, "💀", "skull", "death dead skeleton", false),
    (0, "☠️", "skull and bones", "danger poison pirate", false),
    (0, "💩", "poop", "poo silly", false),
    (0, "🤡", "clown", "circus silly", false),
    (0, "👹", "ogre", "monster demon", false),
    (0, "👺", "long nosed goblin", "monster tengu", false),
    (0, "👻", "ghost", "boo spooky halloween", false),
    (0, "👽", "alien", "ufo space extraterrestrial", false),
    (0, "👾", "space monster", "alien game arcade", false),
    (0, "🤖", "robot", "bot machine", false),
    (0, "😺", "smiling cat", "pet happy", false),
    (0, "😸", "grinning cat", "pet happy", false),
    (0, "😹", "laughing cat", "lol tears funny", false),
    (0, "😻", "heart eyed cat", "love pet", false),
    (0, "😼", "smirking cat", "sly pet", false),
    (0, "😽", "kissing cat", "love pet", false),
    (0, "🙀", "shocked cat", "scared pet", false),
    (0, "😿", "crying cat", "sad pet", false),
    (0, "😾", "angry cat", "pouting pet", false),
    (
        0,
        "🙈",
        "monkey covering eyes",
        "see embarrassed shy",
        false,
    ),
    (0, "🙉", "monkey covering ears", "hear ignore", false),
    (0, "🙊", "monkey covering mouth", "speak secret", false),
    (0, "💌", "love letter", "mail romance heart", false),
    (0, "💘", "heart with arrow", "love cupid", false),
    (0, "💝", "heart gift", "love ribbon valentine", false),
    (0, "💖", "sparkling heart", "love sparkle", false),
    (0, "💗", "growing heart", "love affection", false),
    (0, "💓", "beating heart", "love pulse", false),
    (0, "💞", "revolving hearts", "love together", false),
    (0, "💕", "two hearts", "love affection", false),
    (0, "💟", "heart decoration", "love symbol", false),
    (0, "❣️", "heart exclamation", "love emphasis", false),
    (0, "💔", "broken heart", "heartbreak sad", false),
    (0, "❤️‍🔥", "burning heart", "passion love fire", false),
    (0, "❤️‍🩹", "healing heart", "recovery love mend", false),
    (0, "❤️", "red heart", "love like favorite favourite", false),
    (0, "🩷", "pink heart", "love sweet", false),
    (0, "🧡", "orange heart", "love warmth", false),
    (0, "💛", "yellow heart", "love friendship", false),
    (0, "💚", "green heart", "love nature", false),
    (0, "💙", "blue heart", "love trust", false),
    (0, "🩵", "light blue heart", "love sky", false),
    (0, "💜", "purple heart", "love", false),
    (0, "🤎", "brown heart", "love", false),
    (0, "🖤", "black heart", "love dark", false),
    (0, "🩶", "gray heart", "grey love", false),
    (0, "🤍", "white heart", "love peace", false),
    (0, "💋", "kiss mark", "lips love lipstick", false),
    (0, "💯", "hundred points", "100 perfect agree", false),
    (0, "💢", "anger symbol", "mad furious", false),
    (0, "💥", "explosion", "boom crash impact", false),
    (0, "💫", "dizzy stars", "sparkle swirl", false),
    (0, "💦", "sweat drops", "water splash", false),
    (0, "💨", "speed cloud", "fast dash wind", false),
    (0, "🕳️", "hole", "empty pit", false),
    (0, "💬", "speech bubble", "chat message talk", false),
    (0, "👁️‍🗨️", "eye in speech bubble", "witness see", false),
    (0, "🗨️", "left speech bubble", "chat message", false),
    (0, "🗯️", "angry speech bubble", "shout yell", false),
    (0, "💭", "thought bubble", "think dream", false),
    (0, "💤", "sleep symbol", "zzz snooze", false),
    (0, "🫪", "distorted face", "warped overwhelmed", false),
    (0, "🫯", "fight cloud", "brawl quarrel argument", false),
    (1, "👋", "waving hand", "hello hi goodbye bye", true),
    (1, "🤚", "back of raised hand", "stop highfive", true),
    (1, "🖐️", "spread fingers", "five hand", true),
    (1, "✋", "raised hand", "stop high five", true),
    (1, "🖖", "vulcan hand", "spock trek", true),
    (1, "🫱", "right hand", "rightward reach", true),
    (1, "🫲", "left hand", "leftward reach", true),
    (1, "🫳", "palm down", "drop hand", true),
    (1, "🫴", "palm up", "offer hand", true),
    (1, "🫷", "pushing left", "stop hand", true),
    (1, "🫸", "pushing right", "stop hand", true),
    (1, "👌", "OK hand", "okay perfect", true),
    (1, "🤌", "pinched fingers", "italian gesture", true),
    (1, "🤏", "pinching hand", "small little tiny", true),
    (1, "✌️", "victory hand", "peace two", true),
    (1, "🤞", "crossed fingers", "luck hope", true),
    (1, "🫰", "finger heart", "love snap", true),
    (1, "🤟", "love you hand", "ily sign", true),
    (1, "🤘", "rock horns", "metal music", true),
    (1, "🤙", "call me hand", "phone shaka", true),
    (1, "👈", "pointing left", "direction finger", true),
    (1, "👉", "pointing right", "direction finger", true),
    (1, "👆", "pointing up", "direction finger", true),
    (1, "🖕", "middle finger", "rude angry", true),
    (1, "👇", "pointing down", "direction finger", true),
    (1, "☝️", "index finger up", "one attention", true),
    (1, "🫵", "pointing at you", "you finger", true),
    (1, "👍", "thumbs up", "+1 yes like approve good", true),
    (1, "👎", "thumbs down", "-1 no dislike bad", true),
    (1, "✊", "raised fist", "solidarity power", true),
    (1, "👊", "fist bump", "punch bro", true),
    (1, "🤛", "left fist", "bump punch", true),
    (1, "🤜", "right fist", "bump punch", true),
    (1, "👏", "clapping", "applause bravo well done", true),
    (1, "🙌", "raised hands", "hooray celebrate praise", true),
    (1, "🫶", "heart hands", "love care", true),
    (1, "👐", "open hands", "hug welcome", true),
    (1, "🤲", "cupped hands", "prayer receive", true),
    (
        1,
        "🙏",
        "folded hands",
        "please thanks pray gratitude",
        true,
    ),
    (1, "✍️", "writing hand", "write pen", true),
    (1, "💅", "nail polish", "manicure beauty", true),
    (1, "🤳", "selfie", "phone camera", true),
    (1, "💪", "flexed arm", "muscle strong biceps", true),
    (1, "🦾", "robotic arm", "prosthetic accessibility", false),
    (1, "🦿", "prosthetic leg", "accessibility", false),
    (1, "🦵", "leg", "limb kick", true),
    (1, "🦶", "foot", "feet step", true),
    (1, "👂", "ear", "hear listen", true),
    (1, "🦻", "hearing aid ear", "accessibility hear", true),
    (1, "👃", "nose", "smell", true),
    (1, "🧠", "brain", "mind smart think", false),
    (1, "🫀", "anatomical heart", "organ pulse medical", false),
    (1, "🫁", "lungs", "breathing organ medical", false),
    (1, "🦷", "tooth", "teeth dentist", false),
    (1, "🦴", "bone", "skeleton", false),
    (1, "👀", "eyes", "look see watch", false),
    (1, "👁️", "eye", "look see", false),
    (1, "👅", "tongue", "taste", false),
    (1, "👄", "mouth", "lips kiss", false),
    (1, "🫦", "biting lip", "nervous flirt", false),
    (1, "👶", "baby", "infant newborn", true),
    (1, "🧒", "child", "kid young", true),
    (1, "👦", "boy", "child kid", true),
    (1, "👧", "girl", "child kid", true),
    (1, "🧑", "adult person", "human grownup", true),
    (1, "👱", "blond person", "blonde hair", true),
    (1, "👨", "man", "adult male", true),
    (1, "🧔", "bearded person", "beard hair", true),
    (1, "👩", "woman", "adult female", true),
    (1, "🧓", "older person", "elder senior", true),
    (1, "👴", "older man", "grandfather grandpa senior", true),
    (1, "👵", "older woman", "grandmother grandma senior", true),
    (1, "🙍", "frowning person", "sad unhappy", true),
    (1, "🙎", "pouting person", "upset angry", true),
    (1, "🙅", "person saying no", "stop denied refuse", true),
    (1, "🙆", "person saying OK", "okay yes accepted", true),
    (
        1,
        "💁",
        "person tipping hand",
        "help information sassy",
        true,
    ),
    (
        1,
        "🙋",
        "person raising hand",
        "question answer volunteer",
        true,
    ),
    (1, "🧏", "deaf person", "hearing accessibility", true),
    (1, "🙇", "person bowing", "sorry thanks respect", true),
    (1, "🤦", "person facepalming", "disbelief frustrated", true),
    (1, "🤷", "person shrugging", "dunno unsure whatever", true),
    (1, "👮", "police officer", "cop law", true),
    (1, "🕵️", "detective", "spy investigate", true),
    (1, "💂", "guard", "security soldier", true),
    (1, "🥷", "ninja", "stealth fighter", true),
    (1, "👷", "construction worker", "builder hardhat", true),
    (1, "🫅", "crowned person", "royalty monarch", true),
    (1, "🤴", "prince", "royalty king", true),
    (1, "👸", "princess", "royalty queen", true),
    (1, "👳", "person wearing a turban", "headwear", true),
    (1, "👲", "person wearing a skullcap", "hat", true),
    (1, "🧕", "woman wearing a headscarf", "hijab", true),
    (1, "🤵", "person in a tuxedo", "groom suit wedding", true),
    (1, "👰", "person wearing a veil", "bride wedding", true),
    (1, "🤰", "pregnant woman", "pregnancy baby", true),
    (1, "🫃", "pregnant man", "pregnancy baby", true),
    (1, "🫄", "pregnant person", "pregnancy baby", true),
    (1, "🤱", "breastfeeding", "nursing baby milk", true),
    (1, "👼", "baby angel", "cherub halo", true),
    (1, "🎅", "Santa Claus", "christmas santa", true),
    (1, "🤶", "Mrs Claus", "christmas santa", true),
    (1, "🧑‍🎄", "holiday person", "mx claus christmas santa", true),
    (1, "🦸", "superhero", "hero superpower", true),
    (1, "🦹", "supervillain", "villain evil", true),
    (1, "🧙", "mage", "wizard witch magic", true),
    (1, "🧚", "fairy", "wings magic", true),
    (1, "🧛", "vampire", "dracula halloween", true),
    (1, "🧜", "merperson", "mermaid merman ocean", true),
    (1, "🧝", "elf", "fantasy magic", true),
    (1, "🧞", "genie", "wish magic", false),
    (1, "🧟", "zombie", "undead halloween", false),
    (1, "🧌", "troll", "fantasy monster", false),
    (1, "💆", "person getting a massage", "spa relax", true),
    (1, "💇", "person getting a haircut", "barber salon", true),
    (1, "🚶", "walking person", "pedestrian stroll", true),
    (1, "🧍", "standing person", "stand upright", true),
    (1, "🧎", "kneeling person", "kneel", true),
    (1, "🏃", "running person", "runner jogging exercise", true),
    (1, "💃", "dancing woman", "dance party", true),
    (1, "🕺", "dancing man", "dance party", true),
    (1, "🕴️", "levitating person", "suit business hover", true),
    (1, "🧖", "person in a sauna", "steam spa relax", true),
    (1, "🧗", "climbing person", "climber rock", true),
    (1, "🤺", "fencer", "fencing sword sport", false),
    (1, "🏇", "horse rider", "racing jockey", true),
    (1, "⛷️", "skier", "ski snow sport", false),
    (1, "🏂", "snowboarder", "snow sport", true),
    (1, "🏌️", "golfer", "golf sport", true),
    (1, "🏄", "surfer", "surf wave ocean", true),
    (1, "🚣", "rowing person", "boat paddle", true),
    (1, "🏊", "swimmer", "swim pool water", true),
    (1, "⛹️", "person bouncing a ball", "basketball sport", true),
    (1, "🏋️", "weightlifter", "gym strong workout", true),
    (1, "🚴", "cyclist", "bike bicycle sport", true),
    (1, "🚵", "mountain biker", "bike bicycle sport", true),
    (1, "🤸", "person cartwheeling", "gymnastics sport", true),
    (1, "🤽", "water polo player", "pool sport", true),
    (1, "🤾", "handball player", "ball sport", true),
    (1, "🤹", "juggler", "circus skill", true),
    (
        1,
        "🧘",
        "person in lotus pose",
        "yoga meditation relax",
        true,
    ),
    (1, "🛀", "person bathing", "bath tub relax", true),
    (1, "🛌", "person in bed", "sleep rest", true),
    (1, "👪", "family", "parents children", false),
    (1, "🗣️", "speaking silhouette", "talk voice", false),
    (1, "👤", "person silhouette", "profile user", false),
    (1, "👥", "two silhouettes", "users group", false),
    (1, "🫂", "people hugging", "hug comfort", false),
    (1, "👣", "footprints", "feet tracks", false),
    (1, "🧑‍🩰", "ballet dancer", "dance ballerina", true),
    (1, "🫆", "fingerprint", "identity touch biometrics", false),
    (1, "🫈", "hairy creature", "bigfoot sasquatch yeti", false),
    (3, "🐵", "monkey face", "animal primate", false),
    (3, "🐒", "monkey", "animal primate", false),
    (3, "🦍", "gorilla", "ape animal", false),
    (3, "🦧", "orangutan", "ape animal", false),
    (3, "🐶", "dog face", "puppy pet", false),
    (3, "🐕", "dog", "pet canine", false),
    (3, "🦮", "guide dog", "accessibility assistance", false),
    (3, "🐕‍🦺", "service dog", "accessibility assistance", false),
    (3, "🐩", "poodle", "dog pet", false),
    (3, "🐺", "wolf", "animal howl", false),
    (3, "🦊", "fox", "animal", false),
    (3, "🦝", "raccoon", "animal", false),
    (3, "🐱", "cat face", "kitten pet", false),
    (3, "🐈", "cat", "pet feline", false),
    (3, "🐈‍⬛", "black cat", "pet feline", false),
    (3, "🦁", "lion", "animal king", false),
    (3, "🐯", "tiger face", "animal", false),
    (3, "🐅", "tiger", "animal stripes", false),
    (3, "🐆", "leopard", "animal spots", false),
    (3, "🐴", "horse face", "pony animal", false),
    (3, "🫎", "moose", "animal antlers", false),
    (3, "🫏", "donkey", "animal mule", false),
    (3, "🐎", "horse", "animal racing", false),
    (3, "🦄", "unicorn", "magic fantasy horse", false),
    (3, "🦓", "zebra", "animal stripes", false),
    (3, "🦌", "deer", "animal antlers", false),
    (3, "🦬", "bison", "animal buffalo", false),
    (3, "🐮", "cow face", "cattle farm", false),
    (3, "🐂", "ox", "cattle farm", false),
    (3, "🐃", "water buffalo", "cattle farm", false),
    (3, "🐄", "cow", "cattle farm milk", false),
    (3, "🐷", "pig face", "farm animal", false),
    (3, "🐖", "pig", "farm animal", false),
    (3, "🐗", "boar", "wild pig", false),
    (3, "🐽", "pig nose", "snout", false),
    (3, "🐏", "ram", "sheep horns", false),
    (3, "🐑", "sheep", "wool farm", false),
    (3, "🐐", "goat", "farm animal", false),
    (3, "🐪", "one hump camel", "desert animal", false),
    (3, "🐫", "two hump camel", "desert animal", false),
    (3, "🦙", "llama", "alpaca animal", false),
    (3, "🦒", "giraffe", "animal tall", false),
    (3, "🐘", "elephant", "animal trunk", false),
    (3, "🦣", "mammoth", "extinct animal", false),
    (3, "🦏", "rhinoceros", "rhino animal", false),
    (3, "🦛", "hippopotamus", "hippo animal", false),
    (3, "🐭", "mouse face", "rodent animal", false),
    (3, "🐁", "mouse", "rodent animal", false),
    (3, "🐀", "rat", "rodent animal", false),
    (3, "🐹", "hamster", "pet rodent", false),
    (3, "🐰", "rabbit face", "bunny animal", false),
    (3, "🐇", "rabbit", "bunny animal", false),
    (3, "🐿️", "chipmunk", "squirrel animal", false),
    (3, "🦫", "beaver", "dam animal", false),
    (3, "🦔", "hedgehog", "spiky animal", false),
    (3, "🦇", "bat", "animal night", false),
    (3, "🐻", "bear", "animal", false),
    (3, "🐻‍❄️", "polar bear", "arctic animal", false),
    (3, "🐨", "koala", "australia animal", false),
    (3, "🐼", "panda", "bear bamboo", false),
    (3, "🦥", "sloth", "slow animal", false),
    (3, "🦦", "otter", "river animal", false),
    (3, "🦨", "skunk", "smelly animal", false),
    (3, "🦘", "kangaroo", "australia animal", false),
    (3, "🦡", "badger", "animal", false),
    (3, "🐾", "paw prints", "pet tracks", false),
    (3, "🦃", "turkey", "bird thanksgiving", false),
    (3, "🐔", "chicken", "bird farm", false),
    (3, "🐓", "rooster", "bird farm", false),
    (3, "🐣", "hatching chick", "baby bird egg", false),
    (3, "🐤", "chick", "baby bird", false),
    (3, "🐥", "front facing chick", "baby bird", false),
    (3, "🐦", "bird", "animal", false),
    (3, "🐧", "penguin", "bird ice", false),
    (3, "🕊️", "dove", "bird peace", false),
    (3, "🦅", "eagle", "bird", false),
    (3, "🦆", "duck", "bird pond", false),
    (3, "🦢", "swan", "bird lake", false),
    (3, "🦉", "owl", "bird night", false),
    (3, "🦤", "dodo", "extinct bird", false),
    (3, "🪶", "feather", "bird quill", false),
    (3, "🦩", "flamingo", "bird pink", false),
    (3, "🦚", "peacock", "bird feathers", false),
    (3, "🦜", "parrot", "bird tropical", false),
    (3, "🪽", "wing", "bird flight angel", false),
    (3, "🐦‍⬛", "black bird", "crow raven", false),
    (3, "🪿", "goose", "bird honk", false),
    (3, "🐦‍🔥", "phoenix", "bird fire rebirth", false),
    (3, "🪹", "empty nest", "bird home", false),
    (3, "🪺", "nest with eggs", "bird home", false),
    (3, "🐸", "frog", "amphibian", false),
    (3, "🐊", "crocodile", "alligator reptile", false),
    (3, "🐢", "turtle", "tortoise reptile", false),
    (3, "🦎", "lizard", "reptile gecko", false),
    (3, "🐍", "snake", "reptile serpent", false),
    (3, "🐲", "dragon face", "fantasy animal", false),
    (3, "🐉", "dragon", "fantasy animal", false),
    (3, "🦕", "long neck dinosaur", "sauropod prehistoric", false),
    (3, "🦖", "T rex", "dinosaur prehistoric", false),
    (3, "🐳", "spouting whale", "ocean sea", false),
    (3, "🐋", "whale", "ocean sea", false),
    (3, "🐬", "dolphin", "ocean sea", false),
    (3, "🦭", "seal", "ocean sea", false),
    (3, "🐟", "fish", "water sea", false),
    (3, "🐠", "tropical fish", "ocean reef", false),
    (3, "🐡", "pufferfish", "ocean sea", false),
    (3, "🦈", "shark", "ocean sea", false),
    (3, "🐙", "octopus", "ocean tentacles", false),
    (3, "🐚", "seashell", "beach ocean", false),
    (3, "🪸", "coral", "reef ocean", false),
    (3, "🪼", "jellyfish", "ocean sea", false),
    (3, "🦀", "crab", "sea shellfish", false),
    (3, "🦞", "lobster", "sea shellfish", false),
    (3, "🦐", "shrimp", "prawn seafood", false),
    (3, "🦑", "squid", "sea tentacles", false),
    (3, "🐌", "snail", "slow shell", false),
    (3, "🦋", "butterfly", "insect wings", false),
    (3, "🐛", "caterpillar", "bug insect", false),
    (3, "🐜", "ant", "bug insect", false),
    (3, "🐝", "bee", "honey insect", false),
    (3, "🪲", "beetle", "bug insect", false),
    (3, "🐞", "ladybird", "ladybug insect", false),
    (3, "🦗", "cricket", "insect bug", false),
    (3, "🪳", "cockroach", "insect bug", false),
    (3, "🕷️", "spider", "arachnid web", false),
    (3, "🕸️", "spider web", "cobweb halloween", false),
    (3, "🦂", "scorpion", "arachnid sting", false),
    (3, "🦟", "mosquito", "insect bite", false),
    (3, "🪰", "fly", "insect bug", false),
    (3, "🪱", "worm", "earth soil", false),
    (3, "🦠", "microbe", "germ bacteria virus", false),
    (3, "💐", "bouquet", "flowers gift", false),
    (3, "🌸", "cherry blossom", "flower spring", false),
    (3, "💮", "white flower", "blossom", false),
    (3, "🪷", "lotus", "flower pond", false),
    (3, "🏵️", "rosette", "flower award", false),
    (3, "🌹", "rose", "flower love", false),
    (3, "🥀", "wilted flower", "rose sad", false),
    (3, "🌺", "hibiscus", "flower tropical", false),
    (3, "🌻", "sunflower", "flower sunny", false),
    (3, "🌼", "blossom", "flower daisy", false),
    (3, "🌷", "tulip", "flower spring", false),
    (3, "🪻", "hyacinth", "flower spring", false),
    (3, "🌱", "seedling", "sprout growing plant", false),
    (3, "🪴", "potted plant", "houseplant garden", false),
    (3, "🌲", "evergreen", "tree pine forest", false),
    (3, "🌳", "leafy tree", "forest deciduous", false),
    (3, "🌴", "palm tree", "tropical beach", false),
    (3, "🌵", "cactus", "desert plant", false),
    (3, "🌾", "rice plant", "grain harvest", false),
    (3, "🌿", "herb", "leaf plant", false),
    (3, "☘️", "shamrock", "clover ireland", false),
    (3, "🍀", "four leaf clover", "luck plant", false),
    (3, "🍁", "maple leaf", "autumn canada", false),
    (3, "🍂", "fallen leaves", "autumn fall", false),
    (3, "🍃", "leaf in wind", "breeze plant", false),
    (3, "🍄", "mushroom", "fungus toadstool", false),
    (3, "🪵", "wood", "log timber", false),
    (3, "🪨", "rock", "stone", false),
    (3, "🪾", "bare tree", "leafless winter", false),
    (3, "🫍", "orca", "killer whale ocean", false),
    (4, "🍇", "grapes", "fruit wine", false),
    (4, "🍈", "melon", "fruit", false),
    (4, "🍉", "watermelon", "fruit summer", false),
    (4, "🍊", "orange", "tangerine mandarin citrus fruit", false),
    (4, "🍋", "lemon", "citrus fruit sour", false),
    (4, "🍋‍🟩", "lime", "citrus fruit green", false),
    (4, "🍌", "banana", "fruit", false),
    (4, "🍍", "pineapple", "fruit tropical", false),
    (4, "🥭", "mango", "fruit tropical", false),
    (4, "🍎", "red apple", "fruit", false),
    (4, "🍏", "green apple", "fruit", false),
    (4, "🍐", "pear", "fruit", false),
    (4, "🍑", "peach", "fruit", false),
    (4, "🍒", "cherries", "fruit cherry", false),
    (4, "🍓", "strawberry", "fruit berry", false),
    (4, "🫐", "blueberries", "fruit berry", false),
    (4, "🥝", "kiwi fruit", "fruit", false),
    (4, "🍅", "tomato", "vegetable fruit", false),
    (4, "🫒", "olive", "food", false),
    (4, "🥥", "coconut", "fruit tropical", false),
    (4, "🥑", "avocado", "food guacamole", false),
    (4, "🍆", "aubergine", "eggplant vegetable", false),
    (4, "🥔", "potato", "vegetable", false),
    (4, "🥕", "carrot", "vegetable", false),
    (4, "🌽", "corn", "maize vegetable", false),
    (4, "🌶️", "hot pepper", "chili chilli spicy", false),
    (4, "🫑", "bell pepper", "capsicum vegetable", false),
    (4, "🥒", "cucumber", "vegetable pickle", false),
    (4, "🥬", "leafy greens", "lettuce cabbage vegetable", false),
    (4, "🥦", "broccoli", "vegetable", false),
    (4, "🧄", "garlic", "food seasoning", false),
    (4, "🧅", "onion", "vegetable", false),
    (4, "🥜", "peanuts", "nuts food", false),
    (4, "🫘", "beans", "legumes food", false),
    (4, "🌰", "chestnut", "nut food", false),
    (4, "🫚", "ginger", "spice root", false),
    (4, "🫛", "peas", "pod vegetable", false),
    (4, "🍄‍🟫", "brown mushroom", "fungus food", false),
    (4, "🫜", "root vegetable", "beet radish turnip", false),
    (4, "🍞", "bread", "loaf toast", false),
    (4, "🥐", "croissant", "pastry breakfast", false),
    (4, "🥖", "baguette", "bread french", false),
    (4, "🫓", "flatbread", "pita naan roti", false),
    (4, "🥨", "pretzel", "bread snack", false),
    (4, "🥯", "bagel", "bread breakfast", false),
    (4, "🥞", "pancakes", "breakfast syrup", false),
    (4, "🧇", "waffle", "breakfast", false),
    (4, "🧀", "cheese", "dairy wedge", false),
    (4, "🍖", "meat on bone", "food barbecue", false),
    (4, "🍗", "drumstick", "chicken turkey meat", false),
    (4, "🥩", "steak", "meat beef", false),
    (4, "🥓", "bacon", "meat breakfast", false),
    (4, "🍔", "burger", "hamburger fastfood", false),
    (4, "🍟", "fries", "chips potato fastfood", false),
    (4, "🍕", "pizza", "slice cheese", false),
    (4, "🌭", "hot dog", "sausage fastfood", false),
    (4, "🥪", "sandwich", "bread lunch", false),
    (4, "🌮", "taco", "mexican food", false),
    (4, "🌯", "burrito", "wrap mexican", false),
    (4, "🫔", "tamale", "mexican food", false),
    (4, "🥙", "stuffed pita", "kebab falafel sandwich", false),
    (4, "🧆", "falafel", "chickpea food", false),
    (4, "🥚", "egg", "breakfast food", false),
    (4, "🍳", "fried egg", "cooking breakfast pan", false),
    (4, "🥘", "pan of food", "paella dinner", false),
    (4, "🍲", "pot of food", "stew soup", false),
    (4, "🫕", "fondue", "cheese pot", false),
    (4, "🥣", "bowl and spoon", "cereal soup breakfast", false),
    (4, "🥗", "salad", "greens healthy food", false),
    (4, "🍿", "popcorn", "snack movie", false),
    (4, "🧈", "butter", "dairy food", false),
    (4, "🧂", "salt", "seasoning", false),
    (4, "🥫", "canned food", "tin", false),
    (4, "🍱", "bento", "lunch japanese", false),
    (4, "🍘", "rice cracker", "snack japanese", false),
    (4, "🍙", "rice ball", "onigiri japanese", false),
    (4, "🍚", "rice bowl", "cooked food", false),
    (4, "🍛", "curry rice", "food spicy", false),
    (4, "🍜", "noodles", "ramen bowl soup", false),
    (4, "🍝", "spaghetti", "pasta italian", false),
    (4, "🍠", "roasted sweet potato", "yam food", false),
    (4, "🍢", "oden", "skewer japanese", false),
    (4, "🍣", "sushi", "fish japanese", false),
    (4, "🍤", "fried shrimp", "tempura prawn", false),
    (4, "🍥", "fish cake", "naruto swirl", false),
    (4, "🥮", "mooncake", "festival pastry", false),
    (4, "🍡", "dango", "dumpling sweet", false),
    (4, "🥟", "dumpling", "gyoza momo potsticker", false),
    (4, "🥠", "fortune cookie", "prediction snack", false),
    (4, "🥡", "takeaway box", "takeout food", false),
    (4, "🦪", "oyster", "shellfish seafood", false),
    (4, "🍦", "soft serve", "ice cream dessert", false),
    (4, "🍧", "shaved ice", "dessert snow", false),
    (4, "🍨", "ice cream", "dessert scoop", false),
    (4, "🍩", "doughnut", "donut dessert", false),
    (4, "🍪", "cookie", "biscuit snack", false),
    (4, "🎂", "birthday cake", "celebrate dessert", false),
    (4, "🍰", "cake slice", "dessert pastry", false),
    (4, "🧁", "cupcake", "dessert muffin", false),
    (4, "🥧", "pie", "dessert pastry", false),
    (4, "🍫", "chocolate", "candy sweet", false),
    (4, "🍬", "wrapped candy", "sweet sugar", false),
    (4, "🍭", "lollipop", "candy sweet", false),
    (4, "🍮", "custard", "pudding dessert", false),
    (4, "🍯", "honey pot", "sweet bee", false),
    (4, "🍼", "baby bottle", "milk feeding", false),
    (4, "🥛", "milk glass", "drink dairy", false),
    (4, "☕", "hot drink", "coffee tea cup", false),
    (4, "🫖", "teapot", "tea brew", false),
    (4, "🍵", "tea cup", "green matcha drink", false),
    (4, "🍶", "sake", "rice wine drink", false),
    (4, "🍾", "popping bottle", "champagne celebrate", false),
    (4, "🍷", "wine glass", "drink red", false),
    (4, "🍸", "cocktail glass", "martini drink", false),
    (4, "🍹", "tropical drink", "cocktail vacation", false),
    (4, "🍺", "beer mug", "drink ale", false),
    (4, "🍻", "cheers with beer", "toast celebrate", false),
    (4, "🥂", "clinking glasses", "cheers toast champagne", false),
    (4, "🥃", "tumbler", "whisky whiskey drink", false),
    (4, "🫗", "pouring liquid", "drink spill", false),
    (4, "🥤", "straw cup", "soda juice drink", false),
    (4, "🧋", "bubble tea", "boba drink", false),
    (4, "🧃", "juice box", "drink carton", false),
    (4, "🧉", "mate", "drink tea", false),
    (4, "🧊", "ice cube", "cold drink", false),
    (4, "🥢", "chopsticks", "utensils food", false),
    (4, "🍽️", "plate and cutlery", "dining food", false),
    (4, "🍴", "fork and knife", "cutlery dining", false),
    (4, "🥄", "spoon", "cutlery food", false),
    (4, "🔪", "kitchen knife", "cooking cut", false),
    (4, "🫙", "jar", "container preserve", false),
    (4, "🏺", "amphora", "vase vessel", false),
    (
        5,
        "🌍",
        "globe showing Europe and Africa",
        "earth world planet",
        false,
    ),
    (
        5,
        "🌎",
        "globe showing the Americas",
        "earth world planet",
        false,
    ),
    (
        5,
        "🌏",
        "globe showing Asia and Australia",
        "earth world planet",
        false,
    ),
    (5, "🌐", "globe grid", "world internet global", false),
    (5, "🗺️", "world map", "travel geography", false),
    (5, "🗾", "Japan map", "country geography", false),
    (5, "🧭", "compass", "direction navigation", false),
    (5, "🏔️", "snowy mountain", "peak alpine", false),
    (5, "⛰️", "mountain", "peak hiking", false),
    (5, "🌋", "volcano", "eruption lava", false),
    (5, "🗻", "Mount Fuji", "japan mountain", false),
    (5, "🏕️", "campsite", "camping tent outdoors", false),
    (5, "🏖️", "beach and umbrella", "sea holiday vacation", false),
    (5, "🏜️", "desert", "sand dry", false),
    (5, "🏝️", "island", "tropical beach", false),
    (5, "🏞️", "national park", "nature landscape", false),
    (5, "🏟️", "stadium", "sport arena", false),
    (5, "🏛️", "classical building", "museum temple", false),
    (5, "🏗️", "building construction", "crane work", false),
    (5, "🧱", "bricks", "wall building", false),
    (5, "🛖", "hut", "house shelter", false),
    (5, "🏘️", "houses", "neighborhood homes", false),
    (5, "🏚️", "abandoned house", "ruin building", false),
    (5, "🏠", "house", "home building", false),
    (5, "🏡", "house with garden", "home building", false),
    (5, "🏢", "office building", "work business", false),
    (5, "🏣", "Japanese post office", "mail building", false),
    (5, "🏤", "post office", "mail building", false),
    (5, "🏥", "hospital", "medical health building", false),
    (5, "🏦", "bank", "money building", false),
    (5, "🏨", "hotel", "travel accommodation", false),
    (5, "🏩", "love hotel", "heart accommodation", false),
    (5, "🏪", "convenience store", "shop market", false),
    (5, "🏫", "school", "education building", false),
    (5, "🏬", "department store", "shopping mall", false),
    (5, "🏭", "factory", "industry building", false),
    (5, "🏯", "Japanese castle", "fortress building", false),
    (5, "🏰", "castle", "fortress fairy tale", false),
    (5, "💒", "wedding chapel", "marriage church", false),
    (5, "🗼", "Tokyo tower", "japan landmark", false),
    (5, "🗽", "Statue of Liberty", "new york landmark", false),
    (5, "⛪", "church", "christian religion", false),
    (5, "🕌", "mosque", "islam religion", false),
    (5, "🛕", "Hindu temple", "religion worship", false),
    (5, "🕍", "synagogue", "jewish religion", false),
    (5, "⛩️", "shrine gate", "shinto japan", false),
    (5, "🕋", "Kaaba", "mecca islam", false),
    (5, "⛲", "fountain", "water park", false),
    (5, "⛺", "tent", "camp outdoors", false),
    (5, "🌁", "foggy city", "mist weather", false),
    (5, "🌃", "city at night", "stars skyline", false),
    (5, "🏙️", "city skyline", "buildings urban", false),
    (5, "🌄", "sunrise in mountains", "morning dawn", false),
    (5, "🌅", "sunrise over water", "morning dawn", false),
    (5, "🌆", "city at sunset", "dusk evening", false),
    (5, "🌇", "sunset skyline", "dusk evening", false),
    (5, "🌉", "bridge at night", "city lights", false),
    (5, "♨️", "hot spring", "steam bath", false),
    (5, "🎠", "carousel horse", "ride amusement", false),
    (5, "🛝", "playground slide", "park play", false),
    (5, "🎡", "Ferris wheel", "ride amusement", false),
    (5, "🎢", "roller coaster", "ride amusement", false),
    (5, "💈", "barber pole", "haircut salon", false),
    (5, "🎪", "circus tent", "show entertainment", false),
    (5, "🚂", "steam train", "locomotive railway", false),
    (5, "🚃", "railway carriage", "train tram", false),
    (5, "🚄", "fast train", "railway highspeed", false),
    (5, "🚅", "bullet train", "railway shinkansen", false),
    (5, "🚆", "train", "railway travel", false),
    (5, "🚇", "subway", "metro underground", false),
    (5, "🚈", "light rail", "train transit", false),
    (5, "🚉", "station", "railway train", false),
    (5, "🚊", "tram", "transit streetcar", false),
    (5, "🚝", "monorail", "train transit", false),
    (5, "🚞", "mountain train", "railway", false),
    (5, "🚋", "tram carriage", "streetcar transit", false),
    (5, "🚌", "bus", "transit vehicle", false),
    (5, "🚍", "approaching bus", "transit vehicle", false),
    (5, "🚎", "trolleybus", "transit vehicle", false),
    (5, "🚐", "minibus", "van vehicle", false),
    (5, "🚑", "ambulance", "emergency medical", false),
    (5, "🚒", "fire engine", "emergency rescue", false),
    (5, "🚓", "police car", "cop emergency", false),
    (5, "🚔", "approaching police car", "cop vehicle", false),
    (5, "🚕", "taxi", "cab vehicle", false),
    (5, "🚖", "approaching taxi", "cab vehicle", false),
    (5, "🚗", "car", "automobile drive", false),
    (5, "🚘", "approaching car", "automobile vehicle", false),
    (5, "🚙", "SUV", "car vehicle", false),
    (5, "🛻", "pickup truck", "vehicle", false),
    (5, "🚚", "delivery truck", "lorry vehicle", false),
    (5, "🚛", "articulated truck", "lorry transport", false),
    (5, "🚜", "tractor", "farm vehicle", false),
    (5, "🏎️", "racing car", "formula motorsport", false),
    (5, "🏍️", "motorcycle", "motorbike vehicle", false),
    (5, "🛵", "motor scooter", "moped vehicle", false),
    (
        5,
        "🦽",
        "manual wheelchair",
        "accessibility mobility",
        false,
    ),
    (
        5,
        "🦼",
        "powered wheelchair",
        "accessibility mobility",
        false,
    ),
    (5, "🛺", "auto rickshaw", "tuktuk vehicle", false),
    (5, "🚲", "bicycle", "bike cycle", false),
    (5, "🛴", "kick scooter", "ride transport", false),
    (5, "🛹", "skateboard", "skate ride", false),
    (5, "🛼", "roller skate", "skating wheels", false),
    (5, "🚏", "bus stop", "transit station", false),
    (5, "🛣️", "highway", "road motorway", false),
    (5, "🛤️", "rail tracks", "railway train", false),
    (5, "🛢️", "oil drum", "barrel fuel", false),
    (5, "⛽", "fuel pump", "gas petrol station", false),
    (5, "🛞", "wheel", "tyre tire", false),
    (5, "🚨", "siren light", "alert police emergency", false),
    (5, "🚥", "horizontal traffic lights", "signal road", false),
    (5, "🚦", "vertical traffic lights", "signal road", false),
    (5, "🛑", "stop sign", "road traffic", false),
    (5, "🚧", "construction barrier", "road work", false),
    (5, "⚓", "anchor", "boat nautical", false),
    (5, "🛟", "life ring", "rescue water", false),
    (5, "⛵", "sailboat", "yacht sea", false),
    (5, "🛶", "canoe", "kayak boat", false),
    (5, "🚤", "speedboat", "boat sea", false),
    (5, "🛳️", "passenger ship", "cruise boat", false),
    (5, "⛴️", "ferry", "boat sea", false),
    (5, "🛥️", "motorboat", "boat sea", false),
    (5, "🚢", "ship", "boat sea", false),
    (5, "✈️", "airplane", "plane flight travel", false),
    (5, "🛩️", "small airplane", "plane flight", false),
    (5, "🛫", "plane taking off", "departure flight", false),
    (5, "🛬", "plane landing", "arrival flight", false),
    (5, "🪂", "parachute", "skydive flight", false),
    (5, "💺", "seat", "chair plane", false),
    (5, "🚁", "helicopter", "flight chopper", false),
    (5, "🚟", "suspended railway", "train cable", false),
    (5, "🚠", "mountain cable car", "gondola lift", false),
    (5, "🚡", "aerial tramway", "cable gondola", false),
    (5, "🛰️", "satellite", "space orbit", false),
    (5, "🚀", "rocket", "space launch", false),
    (5, "🛸", "flying saucer", "ufo alien", false),
    (5, "🛎️", "service bell", "hotel reception", false),
    (5, "🧳", "luggage", "suitcase travel", false),
    (5, "⌛", "finished hourglass", "time sand", false),
    (5, "⏳", "running hourglass", "time wait", false),
    (5, "⌚", "watch", "time wrist", false),
    (5, "⏰", "alarm clock", "time wake", false),
    (5, "⏱️", "stopwatch", "time race", false),
    (5, "⏲️", "timer", "time countdown", false),
    (5, "🕰️", "mantel clock", "time antique", false),
    (5, "🕛", "twelve o'clock", "time 12:00 noon midnight", false),
    (5, "🕧", "half past twelve", "time 12:30", false),
    (5, "🕐", "one o'clock", "time 1:00", false),
    (5, "🕜", "half past one", "time 1:30", false),
    (5, "🕑", "two o'clock", "time 2:00", false),
    (5, "🕝", "half past two", "time 2:30", false),
    (5, "🕒", "three o'clock", "time 3:00", false),
    (5, "🕞", "half past three", "time 3:30", false),
    (5, "🕓", "four o'clock", "time 4:00", false),
    (5, "🕟", "half past four", "time 4:30", false),
    (5, "🕔", "five o'clock", "time 5:00", false),
    (5, "🕠", "half past five", "time 5:30", false),
    (5, "🕕", "six o'clock", "time 6:00", false),
    (5, "🕡", "half past six", "time 6:30", false),
    (5, "🕖", "seven o'clock", "time 7:00", false),
    (5, "🕢", "half past seven", "time 7:30", false),
    (5, "🕗", "eight o'clock", "time 8:00", false),
    (5, "🕣", "half past eight", "time 8:30", false),
    (5, "🕘", "nine o'clock", "time 9:00", false),
    (5, "🕤", "half past nine", "time 9:30", false),
    (5, "🕙", "ten o'clock", "time 10:00", false),
    (5, "🕥", "half past ten", "time 10:30", false),
    (5, "🕚", "eleven o'clock", "time 11:00", false),
    (5, "🕦", "half past eleven", "time 11:30", false),
    (5, "🌑", "new moon", "night lunar", false),
    (5, "🌒", "waxing crescent moon", "night lunar", false),
    (5, "🌓", "first quarter moon", "night lunar", false),
    (5, "🌔", "waxing gibbous moon", "night lunar", false),
    (5, "🌕", "full moon", "night lunar", false),
    (5, "🌖", "waning gibbous moon", "night lunar", false),
    (5, "🌗", "last quarter moon", "night lunar", false),
    (5, "🌘", "waning crescent moon", "night lunar", false),
    (5, "🌙", "crescent moon", "night lunar", false),
    (5, "🌚", "dark moon face", "night lunar", false),
    (5, "🌛", "first quarter moon face", "night lunar", false),
    (5, "🌜", "last quarter moon face", "night lunar", false),
    (5, "🌡️", "thermometer", "temperature weather", false),
    (5, "☀️", "sun", "sunny weather", false),
    (5, "🌝", "full moon face", "night lunar", false),
    (5, "🌞", "sun face", "sunny morning", false),
    (5, "🪐", "ringed planet", "saturn space", false),
    (5, "⭐", "star", "night favorite favourite", false),
    (5, "🌟", "glowing star", "shine sparkle", false),
    (5, "🌠", "shooting star", "wish meteor", false),
    (5, "🌌", "Milky Way", "galaxy space stars", false),
    (5, "☁️", "cloud", "weather sky", false),
    (5, "⛅", "sun behind cloud", "weather partly sunny", false),
    (5, "⛈️", "storm cloud", "thunder lightning rain", false),
    (
        5,
        "🌤️",
        "sun with small cloud",
        "weather partly cloudy",
        false,
    ),
    (5, "🌥️", "sun with large cloud", "weather cloudy", false),
    (5, "🌦️", "sun and rain", "weather shower", false),
    (5, "🌧️", "rain cloud", "weather wet", false),
    (5, "🌨️", "snow cloud", "weather winter", false),
    (5, "🌩️", "lightning cloud", "weather storm", false),
    (5, "🌪️", "tornado", "weather twister", false),
    (5, "🌫️", "fog", "weather mist", false),
    (5, "🌬️", "blowing wind", "weather breeze", false),
    (5, "🌀", "cyclone", "swirl storm", false),
    (5, "🌈", "rainbow", "colors weather pride", false),
    (5, "🌂", "closed umbrella", "rain weather", false),
    (5, "☂️", "umbrella", "rain weather", false),
    (5, "☔", "umbrella in rain", "wet weather", false),
    (5, "⛱️", "beach umbrella", "sun shade holiday", false),
    (5, "⚡", "lightning bolt", "electric energy fast", false),
    (5, "❄️", "snowflake", "cold winter", false),
    (5, "☃️", "snowman in snow", "winter cold", false),
    (5, "⛄", "snowman", "winter cold", false),
    (5, "☄️", "comet", "space meteor", false),
    (5, "🔥", "fire", "hot lit flame", false),
    (5, "💧", "water drop", "liquid drip", false),
    (5, "🌊", "wave", "ocean sea surf", false),
    (5, "🛘", "landslide", "rocks avalanche", false),
    (
        6,
        "🎃",
        "pumpkin lantern",
        "halloween jack o lantern",
        false,
    ),
    (6, "🎄", "Christmas tree", "holiday festive", false),
    (6, "🎆", "fireworks", "celebrate festival", false),
    (6, "🎇", "sparkler", "celebrate festival", false),
    (6, "🧨", "firecracker", "bang explosive", false),
    (6, "✨", "sparkles", "magic shine clean", false),
    (6, "🎈", "balloon", "party birthday", false),
    (
        6,
        "🎉",
        "party popper",
        "tada celebrate congratulations",
        false,
    ),
    (6, "🎊", "confetti ball", "party celebrate", false),
    (6, "🎋", "wish tree", "tanabata bamboo", false),
    (6, "🎍", "pine decoration", "new year kadomatsu", false),
    (6, "🎎", "Japanese dolls", "festival hina", false),
    (6, "🎏", "carp windsocks", "koinobori festival", false),
    (6, "🎐", "wind chime", "bell summer", false),
    (6, "🎑", "moon viewing", "harvest festival", false),
    (6, "🧧", "red envelope", "gift luck money", false),
    (6, "🎀", "ribbon", "bow gift", false),
    (6, "🎁", "wrapped present", "gift birthday", false),
    (6, "🎗️", "awareness ribbon", "support cause", false),
    (6, "🎟️", "admission tickets", "event entry", false),
    (6, "🎫", "ticket", "event entry", false),
    (6, "🎖️", "military medal", "honor award", false),
    (6, "🏆", "trophy", "winner champion award", false),
    (6, "🏅", "sports medal", "award winner", false),
    (6, "🥇", "gold medal", "first 1st winner", false),
    (6, "🥈", "silver medal", "second 2nd award", false),
    (6, "🥉", "bronze medal", "third 3rd award", false),
    (6, "⚽", "soccer ball", "football sport", false),
    (6, "⚾", "baseball", "sport ball", false),
    (6, "🥎", "softball", "sport ball", false),
    (6, "🏀", "basketball", "sport ball", false),
    (6, "🏐", "volleyball", "sport ball", false),
    (6, "🏈", "American football", "sport ball", false),
    (6, "🏉", "rugby ball", "sport", false),
    (6, "🎾", "tennis", "sport racket", false),
    (6, "🥏", "flying disc", "frisbee sport", false),
    (6, "🎳", "bowling", "pins sport", false),
    (6, "🏏", "cricket bat and ball", "sport", false),
    (6, "🏑", "field hockey", "stick sport", false),
    (6, "🏒", "ice hockey", "puck stick sport", false),
    (6, "🥍", "lacrosse", "sport stick", false),
    (6, "🏓", "table tennis", "ping pong sport", false),
    (6, "🏸", "badminton", "shuttlecock racket sport", false),
    (6, "🥊", "boxing glove", "punch sport", false),
    (6, "🥋", "martial arts uniform", "karate judo sport", false),
    (6, "🥅", "goal net", "sport football", false),
    (6, "⛳", "golf flag", "hole sport", false),
    (6, "⛸️", "ice skate", "winter sport", false),
    (6, "🎣", "fishing rod", "fish hobby", false),
    (6, "🤿", "diving mask", "snorkel scuba", false),
    (6, "🎽", "running shirt", "athletics sport", false),
    (6, "🎿", "skis", "snow winter sport", false),
    (6, "🛷", "sled", "snow winter", false),
    (6, "🥌", "curling stone", "ice sport", false),
    (6, "🎯", "bullseye", "target darts aim", false),
    (6, "🪀", "yo-yo", "toy game", false),
    (6, "🪁", "kite", "wind flying", false),
    (6, "🔫", "water pistol", "toy squirt gun", false),
    (6, "🎱", "billiard ball", "pool eight game", false),
    (6, "🔮", "crystal ball", "fortune magic", false),
    (6, "🪄", "magic wand", "wizard spell", false),
    (
        6,
        "🎮",
        "game controller",
        "gaming console videogame",
        false,
    ),
    (6, "🕹️", "joystick", "game arcade", false),
    (6, "🎰", "slot machine", "casino jackpot", false),
    (6, "🎲", "die", "dice game random", false),
    (6, "🧩", "puzzle piece", "jigsaw game", false),
    (6, "🧸", "teddy bear", "toy hug", false),
    (6, "🪅", "piñata", "pinata party", false),
    (6, "🪩", "mirror ball", "disco dance", false),
    (6, "🪆", "nesting dolls", "matryoshka toy", false),
    (6, "♠️", "spade suit", "cards game", false),
    (6, "♥️", "heart suit", "cards game", false),
    (6, "♦️", "diamond suit", "cards game", false),
    (6, "♣️", "club suit", "cards game", false),
    (6, "♟️", "chess pawn", "game strategy", false),
    (6, "🃏", "joker card", "cards game", false),
    (6, "🀄", "mahjong tile", "red dragon game", false),
    (6, "🎴", "flower cards", "hanafuda game", false),
    (6, "🎭", "theater masks", "drama acting theatre", false),
    (6, "🖼️", "framed picture", "art painting", false),
    (6, "🎨", "paint palette", "art colors", false),
    (6, "🧵", "thread", "sewing spool", false),
    (6, "🪡", "needle", "sewing stitch", false),
    (6, "🧶", "yarn", "knitting wool", false),
    (6, "🪢", "knot", "rope tie", false),
    (7, "👓", "glasses", "eyewear vision", false),
    (7, "🕶️", "sunglasses", "cool sun eyewear", false),
    (7, "🥽", "goggles", "safety swimming", false),
    (7, "🥼", "lab coat", "science doctor", false),
    (7, "🦺", "safety vest", "visibility worker", false),
    (7, "👔", "necktie", "shirt formal", false),
    (7, "👕", "T-shirt", "clothing tee", false),
    (7, "👖", "jeans", "pants denim", false),
    (7, "🧣", "scarf", "clothing winter", false),
    (7, "🧤", "gloves", "clothing winter", false),
    (7, "🧥", "coat", "jacket clothing", false),
    (7, "🧦", "socks", "clothing feet", false),
    (7, "👗", "dress", "clothing fashion", false),
    (7, "👘", "kimono", "clothing japanese", false),
    (7, "🥻", "sari", "saree clothing", false),
    (7, "🩱", "swimsuit", "swim clothing", false),
    (7, "🩲", "briefs", "underwear clothing", false),
    (7, "🩳", "shorts", "clothing summer", false),
    (7, "👙", "bikini", "swim clothing", false),
    (7, "👚", "blouse", "shirt clothing", false),
    (7, "🪭", "folding fan", "cool air", false),
    (7, "👛", "coin purse", "money bag", false),
    (7, "👜", "handbag", "purse fashion", false),
    (7, "👝", "clutch bag", "purse fashion", false),
    (7, "🛍️", "shopping bags", "buy store", false),
    (7, "🎒", "backpack", "school bag", false),
    (7, "🩴", "flip flop", "sandal shoe", false),
    (7, "👞", "dress shoe", "footwear", false),
    (7, "👟", "sneaker", "trainer shoe running", false),
    (7, "🥾", "hiking boot", "shoe walking", false),
    (7, "🥿", "flat shoe", "ballet footwear", false),
    (7, "👠", "high heel", "shoe footwear", false),
    (7, "👡", "sandal", "shoe summer", false),
    (7, "🩰", "ballet shoes", "dance footwear", false),
    (7, "👢", "boot", "shoe footwear", false),
    (7, "🪮", "hair comb", "styling grooming", false),
    (7, "👑", "crown", "royalty king queen", false),
    (7, "👒", "sun hat", "clothing summer", false),
    (7, "🎩", "top hat", "formal magic", false),
    (7, "🎓", "graduation cap", "college school", false),
    (7, "🧢", "baseball cap", "hat clothing", false),
    (7, "🪖", "military helmet", "army protection", false),
    (7, "⛑️", "rescue helmet", "safety first aid", false),
    (7, "📿", "prayer beads", "religion meditation", false),
    (7, "💄", "lipstick", "makeup beauty", false),
    (7, "💍", "ring", "engagement wedding jewelry", false),
    (7, "💎", "gem", "diamond jewel", false),
    (7, "🔇", "muted speaker", "silent sound off", false),
    (7, "🔈", "quiet speaker", "low volume sound", false),
    (7, "🔉", "medium speaker", "volume sound", false),
    (7, "🔊", "loud speaker", "high volume sound", false),
    (7, "📢", "loudspeaker", "announcement sound", false),
    (7, "📣", "megaphone", "cheer announcement", false),
    (7, "📯", "postal horn", "music sound", false),
    (7, "🔔", "bell", "notification sound", false),
    (7, "🔕", "muted bell", "notification silent", false),
    (7, "🎼", "musical score", "music notation", false),
    (7, "🎵", "music note", "song melody", false),
    (7, "🎶", "music notes", "song melody", false),
    (7, "🎙️", "studio microphone", "recording podcast", false),
    (7, "🎚️", "level slider", "audio mixing", false),
    (7, "🎛️", "control knobs", "audio mixing", false),
    (7, "🎤", "microphone", "sing karaoke", false),
    (7, "🎧", "headphones", "listen music audio", false),
    (7, "📻", "radio", "broadcast music", false),
    (7, "🎷", "saxophone", "instrument jazz", false),
    (7, "🪗", "accordion", "instrument music", false),
    (7, "🎸", "guitar", "instrument rock", false),
    (7, "🎹", "piano keyboard", "instrument music", false),
    (7, "🎺", "trumpet", "instrument brass", false),
    (7, "🎻", "violin", "instrument strings", false),
    (7, "🪕", "banjo", "instrument strings", false),
    (7, "🥁", "drum", "instrument percussion", false),
    (7, "🪘", "hand drum", "instrument percussion", false),
    (7, "🪇", "maracas", "instrument shake", false),
    (7, "🪈", "flute", "instrument woodwind", false),
    (7, "🪉", "harp", "instrument strings", false),
    (7, "📱", "mobile phone", "cell smartphone", false),
    (7, "📲", "incoming phone", "call message", false),
    (7, "☎️", "telephone", "landline call", false),
    (7, "📞", "phone receiver", "call telephone", false),
    (7, "📟", "pager", "beeper device", false),
    (7, "📠", "fax machine", "office document", false),
    (7, "🔋", "battery", "power charge", false),
    (7, "🪫", "low battery", "empty power", false),
    (7, "🔌", "electric plug", "power socket", false),
    (7, "💻", "laptop", "computer work", false),
    (7, "🖥️", "desktop computer", "monitor screen", false),
    (7, "🖨️", "printer", "office paper", false),
    (7, "⌨️", "keyboard", "typing computer", false),
    (7, "🖱️", "computer mouse", "click pointer", false),
    (7, "🖲️", "trackball", "computer pointer", false),
    (7, "💽", "computer disc", "minidisc storage", false),
    (7, "💾", "floppy disk", "save storage", false),
    (7, "💿", "CD", "disc music", false),
    (7, "📀", "DVD", "disc movie", false),
    (7, "🧮", "abacus", "count maths math", false),
    (7, "🎥", "movie camera", "film cinema", false),
    (7, "🎞️", "film strip", "movie frames", false),
    (7, "📽️", "film projector", "cinema movie", false),
    (7, "🎬", "clapper board", "movie action", false),
    (7, "📺", "television", "tv screen", false),
    (7, "📷", "camera", "photo picture", false),
    (7, "📸", "camera flash", "photo picture", false),
    (7, "📹", "video camera", "record movie", false),
    (7, "📼", "video tape", "vhs cassette", false),
    (
        7,
        "🔍",
        "magnifying glass left",
        "search zoom inspect",
        false,
    ),
    (
        7,
        "🔎",
        "magnifying glass right",
        "search zoom inspect",
        false,
    ),
    (7, "🕯️", "candle", "light flame", false),
    (7, "💡", "light bulb", "idea bright", false),
    (7, "🔦", "flashlight", "torch light", false),
    (7, "🏮", "red lantern", "light festival", false),
    (7, "🪔", "oil lamp", "diya light diwali", false),
    (7, "📔", "decorated notebook", "journal writing", false),
    (7, "📕", "closed book", "read study", false),
    (7, "📖", "open book", "read study", false),
    (7, "📗", "green book", "read study", false),
    (7, "📘", "blue book", "read study", false),
    (7, "📙", "orange book", "read study", false),
    (7, "📚", "stack of books", "library read", false),
    (7, "📓", "notebook", "journal writing", false),
    (7, "📒", "ledger", "accounting notebook", false),
    (7, "📃", "curled page", "paper document", false),
    (7, "📜", "scroll", "paper document", false),
    (7, "📄", "page", "paper document", false),
    (7, "📰", "newspaper", "news press", false),
    (7, "🗞️", "rolled newspaper", "news press", false),
    (7, "📑", "bookmark tabs", "pages document", false),
    (7, "🔖", "bookmark", "save read", false),
    (7, "🏷️", "label", "tag price", false),
    (7, "💰", "money bag", "cash wealth", false),
    (7, "🪙", "coin", "money currency", false),
    (7, "💴", "yen banknote", "money currency", false),
    (7, "💵", "dollar banknote", "money cash", false),
    (7, "💶", "euro banknote", "money currency", false),
    (7, "💷", "pound banknote", "money currency", false),
    (7, "💸", "flying money", "spend cash", false),
    (7, "💳", "credit card", "payment bank", false),
    (7, "🧾", "receipt", "bill payment", false),
    (7, "💹", "yen chart", "finance growth", false),
    (7, "✉️", "envelope", "mail letter", false),
    (7, "📧", "email", "mail message", false),
    (7, "📨", "incoming envelope", "mail receive", false),
    (7, "📩", "envelope with arrow", "mail send", false),
    (7, "📤", "outbox", "mail upload", false),
    (7, "📥", "inbox", "mail download", false),
    (7, "📦", "package", "parcel delivery", false),
    (7, "📫", "closed mailbox raised flag", "mail post", false),
    (7, "📪", "closed mailbox lowered flag", "mail post", false),
    (7, "📬", "open mailbox raised flag", "mail post", false),
    (7, "📭", "open mailbox lowered flag", "mail post", false),
    (7, "📮", "postbox", "mail letter", false),
    (7, "🗳️", "ballot box", "vote election", false),
    (7, "✏️", "pencil", "write draw", false),
    (7, "✒️", "pen nib", "write ink", false),
    (7, "🖋️", "fountain pen", "write ink", false),
    (7, "🖊️", "ballpoint pen", "write ink", false),
    (7, "🖌️", "paintbrush", "paint art", false),
    (7, "🖍️", "crayon", "draw color", false),
    (7, "📝", "memo", "note write", false),
    (7, "💼", "briefcase", "business work", false),
    (7, "📁", "folder", "files documents", false),
    (7, "📂", "open folder", "files documents", false),
    (7, "🗂️", "file dividers", "index documents", false),
    (7, "📅", "calendar", "date schedule", false),
    (7, "📆", "tear off calendar", "date schedule", false),
    (7, "🗒️", "spiral notepad", "notes writing", false),
    (7, "🗓️", "spiral calendar", "date schedule", false),
    (7, "📇", "card index", "contacts rolodex", false),
    (7, "📈", "rising chart", "growth increase graph", false),
    (7, "📉", "falling chart", "decline decrease graph", false),
    (7, "📊", "bar chart", "data graph", false),
    (7, "📋", "clipboard", "list notes", false),
    (7, "📌", "pushpin", "pin location", false),
    (7, "📍", "round pin", "location map", false),
    (7, "📎", "paperclip", "attachment office", false),
    (7, "🖇️", "linked paperclips", "attachment office", false),
    (7, "📏", "ruler", "measure straight", false),
    (7, "📐", "triangle ruler", "measure geometry", false),
    (7, "✂️", "scissors", "cut craft", false),
    (7, "🗃️", "card file box", "archive storage", false),
    (7, "🗄️", "filing cabinet", "archive storage", false),
    (7, "🗑️", "wastebasket", "trash bin delete", false),
    (7, "🔒", "locked padlock", "secure private", false),
    (7, "🔓", "unlocked padlock", "open access", false),
    (7, "🔏", "lock with pen", "privacy sign", false),
    (7, "🔐", "lock and key", "secure private", false),
    (7, "🔑", "key", "unlock access", false),
    (7, "🗝️", "old key", "unlock access", false),
    (7, "🔨", "hammer", "tool build", false),
    (7, "🪓", "axe", "tool chop", false),
    (7, "⛏️", "pickaxe", "tool mining", false),
    (7, "⚒️", "hammer and pick", "tools work", false),
    (7, "🛠️", "hammer and wrench", "tools repair", false),
    (7, "🗡️", "dagger", "blade weapon", false),
    (7, "⚔️", "crossed swords", "battle weapon", false),
    (7, "💣", "bomb", "explosive boom", false),
    (7, "🪃", "boomerang", "throw return", false),
    (7, "🏹", "bow and arrow", "archery sport", false),
    (7, "🛡️", "shield", "protect defense", false),
    (7, "🪚", "saw", "tool cut wood", false),
    (7, "🔧", "wrench", "tool repair spanner", false),
    (7, "🪛", "screwdriver", "tool repair", false),
    (7, "🔩", "nut and bolt", "hardware screw", false),
    (7, "⚙️", "gear", "settings cog", false),
    (7, "🗜️", "clamp", "tool vice", false),
    (7, "⚖️", "scales", "balance justice", false),
    (7, "🦯", "white cane", "blind accessibility", false),
    (7, "🔗", "chain link", "url connect", false),
    (7, "⛓️", "chains", "links connect", false),
    (7, "⛓️‍💥", "broken chain", "freedom release", false),
    (7, "🪝", "hook", "hang tool", false),
    (7, "🧰", "toolbox", "repair tools", false),
    (7, "🧲", "magnet", "attract metal", false),
    (7, "🪜", "ladder", "climb steps", false),
    (7, "⚗️", "alembic", "chemistry distill", false),
    (7, "🧪", "test tube", "science experiment", false),
    (7, "🧫", "petri dish", "biology laboratory", false),
    (7, "🧬", "DNA", "genetics helix", false),
    (7, "🔬", "microscope", "science laboratory", false),
    (7, "🔭", "telescope", "space astronomy", false),
    (7, "📡", "satellite dish", "signal broadcast", false),
    (7, "💉", "syringe", "injection vaccine medical", false),
    (7, "🩸", "blood drop", "donation medical", false),
    (7, "💊", "pill", "medicine tablet", false),
    (7, "🩹", "bandage", "first aid plaster", false),
    (7, "🩼", "crutch", "injury accessibility", false),
    (7, "🩺", "stethoscope", "doctor medical", false),
    (7, "🩻", "X ray", "scan bones medical", false),
    (7, "🚪", "door", "entrance exit", false),
    (7, "🛗", "elevator", "lift accessibility", false),
    (7, "🪞", "mirror", "reflection", false),
    (7, "🪟", "window", "view glass", false),
    (7, "🛏️", "bed", "sleep furniture", false),
    (7, "🛋️", "sofa and lamp", "living room furniture", false),
    (7, "🪑", "chair", "seat furniture", false),
    (7, "🚽", "toilet", "bathroom restroom", false),
    (7, "🪠", "plunger", "plumbing bathroom", false),
    (7, "🚿", "shower", "wash bathroom", false),
    (7, "🛁", "bathtub", "bath wash", false),
    (7, "🪤", "mouse trap", "pest bait", false),
    (7, "🪒", "razor", "shave grooming", false),
    (7, "🧴", "lotion bottle", "cream shampoo", false),
    (7, "🧷", "safety pin", "fasten clip", false),
    (7, "🧹", "broom", "clean sweep", false),
    (7, "🧺", "basket", "laundry storage", false),
    (7, "🧻", "paper roll", "toilet tissue", false),
    (7, "🪣", "bucket", "pail cleaning", false),
    (7, "🧼", "soap", "wash clean", false),
    (7, "🫧", "bubbles", "soap clean", false),
    (7, "🪥", "toothbrush", "dental brush", false),
    (7, "🧽", "sponge", "wash clean", false),
    (7, "🧯", "fire extinguisher", "safety emergency", false),
    (7, "🛒", "shopping cart", "trolley groceries", false),
    (7, "🚬", "cigarette", "smoke tobacco", false),
    (7, "⚰️", "coffin", "funeral death", false),
    (7, "🪦", "headstone", "grave cemetery", false),
    (7, "⚱️", "funeral urn", "ashes memorial", false),
    (7, "🧿", "evil eye charm", "nazar protection", false),
    (7, "🪬", "hamsa", "hand protection", false),
    (7, "🗿", "moai", "statue easter island", false),
    (7, "🪧", "placard", "protest sign", false),
    (7, "🪪", "ID card", "identity identification", false),
    (7, "🪏", "shovel", "spade dig garden", false),
    (7, "🪊", "trombone", "instrument brass music", false),
    (7, "🪎", "treasure chest", "gold pirate valuables", false),
    (8, "🏧", "ATM", "cash machine bank", false),
    (8, "🚮", "litter bin sign", "trash disposal", false),
    (8, "🚰", "drinking water", "tap potable", false),
    (
        8,
        "♿",
        "wheelchair symbol",
        "accessibility disability",
        false,
    ),
    (8, "🚹", "men's room", "restroom toilet", false),
    (8, "🚺", "women's room", "restroom toilet", false),
    (8, "🚻", "restroom", "bathroom toilet", false),
    (8, "🚼", "baby changing", "infant nursery", false),
    (8, "🚾", "WC", "toilet bathroom", false),
    (8, "🛂", "passport control", "border travel", false),
    (8, "🛃", "customs", "border luggage", false),
    (8, "🛄", "baggage claim", "luggage airport", false),
    (8, "🛅", "luggage storage", "locker suitcase", false),
    (8, "⚠️", "warning", "caution alert", false),
    (8, "🚸", "children crossing", "school traffic", false),
    (8, "⛔", "no entry", "stop prohibited", false),
    (8, "🚫", "prohibited", "forbidden banned no", false),
    (8, "🚳", "no bicycles", "bike prohibited", false),
    (8, "🚭", "no smoking", "cigarette prohibited", false),
    (8, "🚯", "no littering", "trash prohibited", false),
    (8, "🚱", "non drinking water", "unsafe tap", false),
    (8, "🚷", "no pedestrians", "walking prohibited", false),
    (8, "📵", "no mobile phones", "phone prohibited", false),
    (8, "🔞", "adults only", "18 restricted underage", false),
    (8, "☢️", "radioactive", "radiation hazard", false),
    (8, "☣️", "biohazard", "danger contamination", false),
    (8, "⬆️", "up arrow", "direction north", false),
    (8, "↗️", "up right arrow", "northeast direction", false),
    (8, "➡️", "right arrow", "east direction", false),
    (8, "↘️", "down right arrow", "southeast direction", false),
    (8, "⬇️", "down arrow", "south direction", false),
    (8, "↙️", "down left arrow", "southwest direction", false),
    (8, "⬅️", "left arrow", "west direction", false),
    (8, "↖️", "up left arrow", "northwest direction", false),
    (8, "↕️", "up down arrow", "vertical direction", false),
    (8, "↔️", "left right arrow", "horizontal direction", false),
    (8, "↩️", "return left arrow", "back reply", false),
    (8, "↪️", "return right arrow", "forward", false),
    (8, "⤴️", "curving up arrow", "direction", false),
    (8, "⤵️", "curving down arrow", "direction", false),
    (8, "🔃", "clockwise arrows", "reload rotate", false),
    (8, "🔄", "counterclockwise arrows", "refresh sync", false),
    (8, "🔙", "back arrow", "return", false),
    (8, "🔚", "end arrow", "finish", false),
    (8, "🔛", "on arrow", "enabled", false),
    (8, "🔜", "soon arrow", "later", false),
    (8, "🔝", "top arrow", "up", false),
    (8, "🛐", "place of worship", "religion prayer", false),
    (8, "⚛️", "atom", "science physics", false),
    (8, "🕉️", "Om", "hindu religion", false),
    (8, "✡️", "Star of David", "jewish religion", false),
    (8, "☸️", "wheel of dharma", "buddhist religion", false),
    (8, "☯️", "yin yang", "balance tao", false),
    (8, "✝️", "Latin cross", "christian religion", false),
    (8, "☦️", "Orthodox cross", "christian religion", false),
    (8, "☪️", "star and crescent", "islam religion", false),
    (8, "☮️", "peace sign", "harmony", false),
    (8, "🕎", "menorah", "jewish religion", false),
    (8, "🔯", "dotted six point star", "symbol", false),
    (8, "🪯", "khanda", "sikh religion", false),
    (8, "♈", "Aries", "zodiac ram", false),
    (8, "♉", "Taurus", "zodiac bull", false),
    (8, "♊", "Gemini", "zodiac twins", false),
    (8, "♋", "Cancer", "zodiac crab", false),
    (8, "♌", "Leo", "zodiac lion", false),
    (8, "♍", "Virgo", "zodiac maiden", false),
    (8, "♎", "Libra", "zodiac scales", false),
    (8, "♏", "Scorpio", "zodiac scorpion", false),
    (8, "♐", "Sagittarius", "zodiac archer", false),
    (8, "♑", "Capricorn", "zodiac goat", false),
    (8, "♒", "Aquarius", "zodiac water bearer", false),
    (8, "♓", "Pisces", "zodiac fish", false),
    (8, "⛎", "Ophiuchus", "zodiac serpent", false),
    (8, "🔀", "shuffle", "random tracks", false),
    (8, "🔁", "repeat", "loop music", false),
    (8, "🔂", "repeat one", "loop track", false),
    (8, "▶️", "play", "start media", false),
    (8, "⏩", "fast forward", "skip media", false),
    (8, "⏭️", "next track", "skip media", false),
    (8, "⏯️", "play pause", "media control", false),
    (8, "◀️", "reverse play", "back media", false),
    (8, "⏪", "rewind", "back media", false),
    (8, "⏮️", "previous track", "back media", false),
    (8, "🔼", "up button", "triangle increase", false),
    (8, "⏫", "fast up", "triangle increase", false),
    (8, "🔽", "down button", "triangle decrease", false),
    (8, "⏬", "fast down", "triangle decrease", false),
    (8, "⏸️", "pause", "media stop", false),
    (8, "⏹️", "stop", "media end", false),
    (8, "⏺️", "record", "media circle", false),
    (8, "⏏️", "eject", "media disc", false),
    (8, "🎦", "cinema sign", "movie film", false),
    (8, "🔅", "dim brightness", "screen low", false),
    (8, "🔆", "bright setting", "screen high", false),
    (8, "📶", "signal bars", "mobile reception", false),
    (8, "🛜", "wireless", "wifi internet", false),
    (8, "📳", "vibration mode", "phone silent", false),
    (8, "📴", "phone off", "mobile disabled", false),
    (8, "♀️", "female sign", "woman venus", false),
    (8, "♂️", "male sign", "man mars", false),
    (8, "⚧️", "transgender sign", "gender pride", false),
    (8, "✖️", "multiply", "times maths math", false),
    (8, "➕", "plus", "add maths math", false),
    (8, "➖", "minus", "subtract maths math", false),
    (8, "➗", "divide", "maths math", false),
    (8, "🟰", "equals", "maths math", false),
    (8, "♾️", "infinity", "forever endless", false),
    (8, "‼️", "double exclamation", "surprise emphasis", false),
    (8, "⁉️", "exclamation question", "confused surprise", false),
    (8, "❓", "red question", "why ask", false),
    (8, "❔", "white question", "why ask", false),
    (8, "❕", "white exclamation", "attention", false),
    (8, "❗", "red exclamation", "attention warning", false),
    (8, "〰️", "wavy dash", "wave line", false),
    (8, "💱", "currency exchange", "money trade", false),
    (8, "💲", "dollar sign", "money currency", false),
    (8, "⚕️", "medical symbol", "health doctor", false),
    (8, "♻️", "recycling", "reuse environment", false),
    (8, "⚜️", "fleur de lis", "lily emblem", false),
    (8, "🔱", "trident", "sea spear", false),
    (8, "📛", "name badge", "identity", false),
    (8, "🔰", "beginner mark", "new learner", false),
    (8, "⭕", "red circle outline", "correct ring", false),
    (8, "✅", "check button", "done yes correct", false),
    (8, "☑️", "checked box", "done selected", false),
    (8, "✔️", "check mark", "done yes correct", false),
    (8, "❌", "cross mark", "no wrong delete", false),
    (8, "❎", "cross button", "no wrong", false),
    (8, "➰", "loop", "curl", false),
    (8, "➿", "double loop", "curl", false),
    (8, "〽️", "part alternation mark", "japanese music", false),
    (8, "✳️", "eight spoke asterisk", "star symbol", false),
    (8, "✴️", "eight point star", "symbol", false),
    (8, "❇️", "sparkle symbol", "star shine", false),
    (8, "©️", "copyright sign", "copyright", false),
    (8, "®️", "registered sign", "registered", false),
    (8, "™️", "trademark sign", "trademark", false),
    (8, "#️⃣", "hash key", "hashtag number keycap", false),
    (8, "*️⃣", "asterisk key", "star keycap", false),
    (8, "0️⃣", "zero key", "0 digit keycap", false),
    (8, "1️⃣", "one key", "1 digit keycap", false),
    (8, "2️⃣", "two key", "2 digit keycap", false),
    (8, "3️⃣", "three key", "3 digit keycap", false),
    (8, "4️⃣", "four key", "4 digit keycap", false),
    (8, "5️⃣", "five key", "5 digit keycap", false),
    (8, "6️⃣", "six key", "6 digit keycap", false),
    (8, "7️⃣", "seven key", "7 digit keycap", false),
    (8, "8️⃣", "eight key", "8 digit keycap", false),
    (8, "9️⃣", "nine key", "9 digit keycap", false),
    (8, "🔟", "ten key", "10 number keycap", false),
    (8, "🔠", "uppercase letters", "ABCD alphabet input", false),
    (8, "🔡", "lowercase letters", "abcd alphabet input", false),
    (8, "🔢", "number input", "1234 digits", false),
    (8, "🔣", "symbol input", "characters", false),
    (8, "🔤", "letter input", "abc alphabet", false),
    (8, "🅰️", "A blood type", "letter", false),
    (8, "🆎", "AB blood type", "letters", false),
    (8, "🅱️", "B blood type", "letter", false),
    (8, "🆑", "CL button", "clear", false),
    (8, "🆒", "cool button", "word", false),
    (8, "🆓", "free button", "gratis", false),
    (8, "ℹ️", "information", "info help", false),
    (8, "🆔", "ID button", "identity", false),
    (8, "Ⓜ️", "circled M", "metro letter", false),
    (8, "🆕", "new button", "fresh", false),
    (8, "🆖", "NG button", "no good", false),
    (8, "🅾️", "O blood type", "letter", false),
    (8, "🆗", "OK button", "okay yes", false),
    (8, "🅿️", "parking button", "letter P", false),
    (8, "🆘", "SOS button", "help emergency", false),
    (8, "🆙", "UP button", "level increase", false),
    (8, "🆚", "VS button", "versus against", false),
    (8, "🈁", "Japanese here button", "location koko", false),
    (8, "🈂️", "Japanese service charge button", "sa", false),
    (8, "🈷️", "Japanese monthly amount button", "moon", false),
    (8, "🈶", "Japanese not free button", "paid", false),
    (8, "🈯", "Japanese reserved button", "seat", false),
    (8, "🉐", "Japanese bargain button", "deal", false),
    (8, "🈹", "Japanese discount button", "sale", false),
    (8, "🈚", "Japanese free button", "gratis", false),
    (8, "🈲", "Japanese prohibited button", "forbidden", false),
    (8, "🉑", "Japanese acceptable button", "okay", false),
    (8, "🈸", "Japanese application button", "apply", false),
    (8, "🈴", "Japanese passing grade button", "exam", false),
    (8, "🈳", "Japanese vacancy button", "empty", false),
    (
        8,
        "㊗️",
        "Japanese congratulations button",
        "celebrate",
        false,
    ),
    (8, "㊙️", "Japanese secret button", "private", false),
    (8, "🈺", "Japanese open for business button", "shop", false),
    (8, "🈵", "Japanese full button", "occupied", false),
    (8, "🔴", "red circle", "shape color", false),
    (8, "🟠", "orange circle", "shape color", false),
    (8, "🟡", "yellow circle", "shape color", false),
    (8, "🟢", "green circle", "shape color", false),
    (8, "🔵", "blue circle", "shape color", false),
    (8, "🟣", "purple circle", "shape color", false),
    (8, "🟤", "brown circle", "shape color", false),
    (8, "⚫", "black circle", "shape color", false),
    (8, "⚪", "white circle", "shape color", false),
    (8, "🟥", "red square", "shape color", false),
    (8, "🟧", "orange square", "shape color", false),
    (8, "🟨", "yellow square", "shape color", false),
    (8, "🟩", "green square", "shape color", false),
    (8, "🟦", "blue square", "shape color", false),
    (8, "🟪", "purple square", "shape color", false),
    (8, "🟫", "brown square", "shape color", false),
    (8, "⬛", "large black square", "shape color", false),
    (8, "⬜", "large white square", "shape color", false),
    (8, "◼️", "medium black square", "shape color", false),
    (8, "◻️", "medium white square", "shape color", false),
    (8, "◾", "small medium black square", "shape color", false),
    (8, "◽", "small medium white square", "shape color", false),
    (8, "▪️", "small black square", "shape color", false),
    (8, "▫️", "small white square", "shape color", false),
    (8, "🔶", "large orange diamond", "shape color", false),
    (8, "🔷", "large blue diamond", "shape color", false),
    (8, "🔸", "small orange diamond", "shape color", false),
    (8, "🔹", "small blue diamond", "shape color", false),
    (8, "🔺", "up red triangle", "shape direction", false),
    (8, "🔻", "down red triangle", "shape direction", false),
    (8, "💠", "diamond with a dot", "shape flower", false),
    (8, "🔘", "radio button", "select circle", false),
    (8, "🔳", "white square button", "shape", false),
    (8, "🔲", "black square button", "shape", false),
    (8, "🫟", "splatter", "paint splash spill", false),
    (9, "🏁", "chequered flag", "checkered race finish", false),
    (9, "🚩", "triangular flag", "red warning", false),
    (9, "🎌", "crossed Japanese flags", "celebrate japan", false),
    (9, "🏴", "black flag", "banner", false),
    (9, "🏳️", "white flag", "surrender peace", false),
    (9, "🏳️‍🌈", "rainbow flag", "pride lgbt gay", false),
    (9, "🏳️‍⚧️", "transgender flag", "pride trans", false),
    (9, "🏴‍☠️", "pirate flag", "skull jolly roger", false),
];

pub(super) const FLAGS: &[(&str, &str)] = &[
    ("AC", "Ascension Island"),
    ("AD", "Andorra"),
    ("AE", "United Arab Emirates"),
    ("AF", "Afghanistan"),
    ("AG", "Antigua and Barbuda"),
    ("AI", "Anguilla"),
    ("AL", "Albania"),
    ("AM", "Armenia"),
    ("AO", "Angola"),
    ("AQ", "Antarctica"),
    ("AR", "Argentina"),
    ("AS", "American Samoa"),
    ("AT", "Austria"),
    ("AU", "Australia"),
    ("AW", "Aruba"),
    ("AX", "Åland Islands"),
    ("AZ", "Azerbaijan"),
    ("BA", "Bosnia and Herzegovina"),
    ("BB", "Barbados"),
    ("BD", "Bangladesh"),
    ("BE", "Belgium"),
    ("BF", "Burkina Faso"),
    ("BG", "Bulgaria"),
    ("BH", "Bahrain"),
    ("BI", "Burundi"),
    ("BJ", "Benin"),
    ("BL", "Saint Barthélemy"),
    ("BM", "Bermuda"),
    ("BN", "Brunei"),
    ("BO", "Bolivia"),
    ("BQ", "Caribbean Netherlands"),
    ("BR", "Brazil"),
    ("BS", "Bahamas"),
    ("BT", "Bhutan"),
    ("BV", "Bouvet Island"),
    ("BW", "Botswana"),
    ("BY", "Belarus"),
    ("BZ", "Belize"),
    ("CA", "Canada"),
    ("CC", "Cocos Islands"),
    ("CD", "Democratic Republic of the Congo"),
    ("CF", "Central African Republic"),
    ("CG", "Republic of the Congo"),
    ("CH", "Switzerland"),
    ("CI", "Côte d’Ivoire Ivory Coast"),
    ("CK", "Cook Islands"),
    ("CL", "Chile"),
    ("CM", "Cameroon"),
    ("CN", "China"),
    ("CO", "Colombia"),
    ("CP", "Clipperton Island"),
    ("CQ", "Sark"),
    ("CR", "Costa Rica"),
    ("CU", "Cuba"),
    ("CV", "Cape Verde"),
    ("CW", "Curaçao"),
    ("CX", "Christmas Island"),
    ("CY", "Cyprus"),
    ("CZ", "Czechia Czech Republic"),
    ("DE", "Germany"),
    ("DG", "Diego Garcia"),
    ("DJ", "Djibouti"),
    ("DK", "Denmark"),
    ("DM", "Dominica"),
    ("DO", "Dominican Republic"),
    ("DZ", "Algeria"),
    ("EA", "Ceuta and Melilla"),
    ("EC", "Ecuador"),
    ("EE", "Estonia"),
    ("EG", "Egypt"),
    ("EH", "Western Sahara"),
    ("ER", "Eritrea"),
    ("ES", "Spain"),
    ("ET", "Ethiopia"),
    ("EU", "European Union"),
    ("FI", "Finland"),
    ("FJ", "Fiji"),
    ("FK", "Falkland Islands"),
    ("FM", "Micronesia"),
    ("FO", "Faroe Islands"),
    ("FR", "France"),
    ("GA", "Gabon"),
    ("GB", "United Kingdom Britain UK"),
    ("GD", "Grenada"),
    ("GE", "Georgia"),
    ("GF", "French Guiana"),
    ("GG", "Guernsey"),
    ("GH", "Ghana"),
    ("GI", "Gibraltar"),
    ("GL", "Greenland"),
    ("GM", "Gambia"),
    ("GN", "Guinea"),
    ("GP", "Guadeloupe"),
    ("GQ", "Equatorial Guinea"),
    ("GR", "Greece"),
    ("GS", "South Georgia and South Sandwich Islands"),
    ("GT", "Guatemala"),
    ("GU", "Guam"),
    ("GW", "Guinea-Bissau"),
    ("GY", "Guyana"),
    ("HK", "Hong Kong"),
    ("HM", "Heard Island and McDonald Islands"),
    ("HN", "Honduras"),
    ("HR", "Croatia"),
    ("HT", "Haiti"),
    ("HU", "Hungary"),
    ("IC", "Canary Islands"),
    ("ID", "Indonesia"),
    ("IE", "Ireland"),
    ("IL", "Israel"),
    ("IM", "Isle of Man"),
    ("IN", "India"),
    ("IO", "British Indian Ocean Territory"),
    ("IQ", "Iraq"),
    ("IR", "Iran"),
    ("IS", "Iceland"),
    ("IT", "Italy"),
    ("JE", "Jersey"),
    ("JM", "Jamaica"),
    ("JO", "Jordan"),
    ("JP", "Japan"),
    ("KE", "Kenya"),
    ("KG", "Kyrgyzstan"),
    ("KH", "Cambodia"),
    ("KI", "Kiribati"),
    ("KM", "Comoros"),
    ("KN", "Saint Kitts and Nevis"),
    ("KP", "North Korea"),
    ("KR", "South Korea"),
    ("KW", "Kuwait"),
    ("KY", "Cayman Islands"),
    ("KZ", "Kazakhstan"),
    ("LA", "Laos"),
    ("LB", "Lebanon"),
    ("LC", "Saint Lucia"),
    ("LI", "Liechtenstein"),
    ("LK", "Sri Lanka"),
    ("LR", "Liberia"),
    ("LS", "Lesotho"),
    ("LT", "Lithuania"),
    ("LU", "Luxembourg"),
    ("LV", "Latvia"),
    ("LY", "Libya"),
    ("MA", "Morocco"),
    ("MC", "Monaco"),
    ("MD", "Moldova"),
    ("ME", "Montenegro"),
    ("MF", "Saint Martin"),
    ("MG", "Madagascar"),
    ("MH", "Marshall Islands"),
    ("MK", "North Macedonia"),
    ("ML", "Mali"),
    ("MM", "Myanmar Burma"),
    ("MN", "Mongolia"),
    ("MO", "Macao Macau"),
    ("MP", "Northern Mariana Islands"),
    ("MQ", "Martinique"),
    ("MR", "Mauritania"),
    ("MS", "Montserrat"),
    ("MT", "Malta"),
    ("MU", "Mauritius"),
    ("MV", "Maldives"),
    ("MW", "Malawi"),
    ("MX", "Mexico"),
    ("MY", "Malaysia"),
    ("MZ", "Mozambique"),
    ("NA", "Namibia"),
    ("NC", "New Caledonia"),
    ("NE", "Niger"),
    ("NF", "Norfolk Island"),
    ("NG", "Nigeria"),
    ("NI", "Nicaragua"),
    ("NL", "Netherlands"),
    ("NO", "Norway"),
    ("NP", "Nepal"),
    ("NR", "Nauru"),
    ("NU", "Niue"),
    ("NZ", "New Zealand"),
    ("OM", "Oman"),
    ("PA", "Panama"),
    ("PE", "Peru"),
    ("PF", "French Polynesia"),
    ("PG", "Papua New Guinea"),
    ("PH", "Philippines"),
    ("PK", "Pakistan"),
    ("PL", "Poland"),
    ("PM", "Saint Pierre and Miquelon"),
    ("PN", "Pitcairn Islands"),
    ("PR", "Puerto Rico"),
    ("PS", "Palestine"),
    ("PT", "Portugal"),
    ("PW", "Palau"),
    ("PY", "Paraguay"),
    ("QA", "Qatar"),
    ("RE", "Réunion"),
    ("RO", "Romania"),
    ("RS", "Serbia"),
    ("RU", "Russia"),
    ("RW", "Rwanda"),
    ("SA", "Saudi Arabia"),
    ("SB", "Solomon Islands"),
    ("SC", "Seychelles"),
    ("SD", "Sudan"),
    ("SE", "Sweden"),
    ("SG", "Singapore"),
    ("SH", "Saint Helena"),
    ("SI", "Slovenia"),
    ("SJ", "Svalbard and Jan Mayen"),
    ("SK", "Slovakia"),
    ("SL", "Sierra Leone"),
    ("SM", "San Marino"),
    ("SN", "Senegal"),
    ("SO", "Somalia"),
    ("SR", "Suriname"),
    ("SS", "South Sudan"),
    ("ST", "São Tomé and Príncipe"),
    ("SV", "El Salvador"),
    ("SX", "Sint Maarten"),
    ("SY", "Syria"),
    ("SZ", "Eswatini Swaziland"),
    ("TA", "Tristan da Cunha"),
    ("TC", "Turks and Caicos Islands"),
    ("TD", "Chad"),
    ("TF", "French Southern Territories"),
    ("TG", "Togo"),
    ("TH", "Thailand"),
    ("TJ", "Tajikistan"),
    ("TK", "Tokelau"),
    ("TL", "Timor-Leste East Timor"),
    ("TM", "Turkmenistan"),
    ("TN", "Tunisia"),
    ("TO", "Tonga"),
    ("TR", "Türkiye Turkey"),
    ("TT", "Trinidad and Tobago"),
    ("TV", "Tuvalu"),
    ("TW", "Taiwan"),
    ("TZ", "Tanzania"),
    ("UA", "Ukraine"),
    ("UG", "Uganda"),
    ("UM", "US Outlying Islands"),
    ("UN", "United Nations"),
    ("US", "United States USA"),
    ("UY", "Uruguay"),
    ("UZ", "Uzbekistan"),
    ("VA", "Vatican City"),
    ("VC", "Saint Vincent and the Grenadines"),
    ("VE", "Venezuela"),
    ("VG", "British Virgin Islands"),
    ("VI", "US Virgin Islands"),
    ("VN", "Vietnam"),
    ("VU", "Vanuatu"),
    ("WF", "Wallis and Futuna"),
    ("WS", "Samoa"),
    ("XK", "Kosovo"),
    ("YE", "Yemen"),
    ("YT", "Mayotte"),
    ("ZA", "South Africa"),
    ("ZM", "Zambia"),
    ("ZW", "Zimbabwe"),
];
